baseURL = 'https://lars147.github.io/blog/'
title = 'Cooking Code'
theme = 'PaperMod'
defaultContentLanguage = 'en'

[languages]
  [languages.en]
    languageCode = 'en-US'
    languageName = 'English'
    weight = 1
    contentDir = 'content/en'
    [languages.en.params]
      subtitle = ''
  [languages.de]
    languageCode = 'de-DE'
    languageName = 'Deutsch'
    weight = 2
    contentDir = 'content/de'
    [languages.de.params]
      subtitle = ''

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
