baseURL = 'https://lars147.github.io/blog/'
languageCode = 'en-us'
title = 'My Blog'
theme = 'PaperMod'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
